{% set name = "pyacoustid" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyacoustid-{{ version }}.tar.gz
  sha256: 5f4f487191c19ebb908270b1b7b5297f132da332b1568b96a914574c079ed177

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - audioread
    - requests

test:
  imports:
    - acoustid
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/sampsyo/pyacoustid
  summary: bindings for Chromaprint acoustic fingerprinting and the Acoustid API
  license: MIT
  license_file: LICENSE
  description: |
    `Chromaprint` and its associated `Acoustid` Web service make up a high-quality, open-source acoustic fingerprinting system. This package provides Python bindings for both the fingerprinting algorithm library, which is written in C but portable, and the Web service, which provides fingerprint lookups.

extra:
  recipe-maintainers:
    - HeavyTony2
